import Foundation

//: [Previous](@previous)

/*:
 ## do-catch
 
 The `do-catch` statement is used to **handle errors** thrown from functions marked with `throws`.
 You write your error-prone code inside the `do` block and handle specific errors in `catch` blocks.
 
 ## Syntax
 ```
 do {
     try STATEMENT
 } catch ERROR {
     STATEMENTS // Handle specific error
 } catch {
     STATEMENTS // Handle any other errors
 }

 ```
 
 */



//: [Next](@next)
